// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: common-example/common-example.proto

package common_example

import (
	_ "github.com/kitt-technology/protoc-gen-graphql/graphql"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Money struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrencyCode  string                 `protobuf:"bytes,1,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	Units         int64                  `protobuf:"varint,2,opt,name=units,proto3" json:"units,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_common_example_common_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_common_example_common_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_common_example_common_example_proto_rawDescGZIP(), []int{0}
}

func (x *Money) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *Money) GetUnits() int64 {
	if x != nil {
		return x.Units
	}
	return 0
}

type Int32Range struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           int32                  `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max           int32                  `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Int32Range) Reset() {
	*x = Int32Range{}
	mi := &file_common_example_common_example_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Int32Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int32Range) ProtoMessage() {}

func (x *Int32Range) ProtoReflect() protoreflect.Message {
	mi := &file_common_example_common_example_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int32Range.ProtoReflect.Descriptor instead.
func (*Int32Range) Descriptor() ([]byte, []int) {
	return file_common_example_common_example_proto_rawDescGZIP(), []int{1}
}

func (x *Int32Range) GetMin() int32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *Int32Range) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type MoneyRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           *Money                 `protobuf:"bytes,1,opt,name=min,proto3" json:"min,omitempty"`
	Max           *Money                 `protobuf:"bytes,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoneyRange) Reset() {
	*x = MoneyRange{}
	mi := &file_common_example_common_example_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoneyRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoneyRange) ProtoMessage() {}

func (x *MoneyRange) ProtoReflect() protoreflect.Message {
	mi := &file_common_example_common_example_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoneyRange.ProtoReflect.Descriptor instead.
func (*MoneyRange) Descriptor() ([]byte, []int) {
	return file_common_example_common_example_proto_rawDescGZIP(), []int{2}
}

func (x *MoneyRange) GetMin() *Money {
	if x != nil {
		return x.Min
	}
	return nil
}

func (x *MoneyRange) GetMax() *Money {
	if x != nil {
		return x.Max
	}
	return nil
}

var File_common_example_common_example_proto protoreflect.FileDescriptor

const file_common_example_common_example_proto_rawDesc = "" +
	"\n" +
	"#common-example/common-example.proto\x12\x0ecommon_example\x1a\rgraphql.proto\"G\n" +
	"\x05Money\x12#\n" +
	"\rcurrency_code\x18\x01 \x01(\tR\fcurrencyCode\x12\x14\n" +
	"\x05units\x18\x02 \x01(\x03R\x05units:\x03\xf8C\x01\"0\n" +
	"\n" +
	"Int32Range\x12\x10\n" +
	"\x03min\x18\x01 \x01(\x05R\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x05R\x03max\"^\n" +
	"\n" +
	"MoneyRange\x12'\n" +
	"\x03min\x18\x01 \x01(\v2\x15.common_example.MoneyR\x03min\x12'\n" +
	"\x03max\x18\x02 \x01(\v2\x15.common_example.MoneyR\x03maxB\xab\x01\x82BSgithub.com/kitt-technology/protoc-gen-graphql/example/common-example;common_exampleZSgithub.com/kitt-technology/protoc-gen-graphql/example/common-example;common_exampleb\x06proto3"

var (
	file_common_example_common_example_proto_rawDescOnce sync.Once
	file_common_example_common_example_proto_rawDescData []byte
)

func file_common_example_common_example_proto_rawDescGZIP() []byte {
	file_common_example_common_example_proto_rawDescOnce.Do(func() {
		file_common_example_common_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_example_common_example_proto_rawDesc), len(file_common_example_common_example_proto_rawDesc)))
	})
	return file_common_example_common_example_proto_rawDescData
}

var file_common_example_common_example_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_common_example_common_example_proto_goTypes = []any{
	(*Money)(nil),      // 0: common_example.Money
	(*Int32Range)(nil), // 1: common_example.Int32Range
	(*MoneyRange)(nil), // 2: common_example.MoneyRange
}
var file_common_example_common_example_proto_depIdxs = []int32{
	0, // 0: common_example.MoneyRange.min:type_name -> common_example.Money
	0, // 1: common_example.MoneyRange.max:type_name -> common_example.Money
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_common_example_common_example_proto_init() }
func file_common_example_common_example_proto_init() {
	if File_common_example_common_example_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_example_common_example_proto_rawDesc), len(file_common_example_common_example_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_example_common_example_proto_goTypes,
		DependencyIndexes: file_common_example_common_example_proto_depIdxs,
		MessageInfos:      file_common_example_common_example_proto_msgTypes,
	}.Build()
	File_common_example_common_example_proto = out.File
	file_common_example_common_example_proto_goTypes = nil
	file_common_example_common_example_proto_depIdxs = nil
}
