// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: products/products.proto

package products

import (
	common_example "github.com/kitt-technology/protoc-gen-graphql/example/common-example"
	graphql "github.com/kitt-technology/protoc-gen-graphql/graphql"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Category int32

const (
	Category_ELECTRONICS Category = 0
	Category_CLOTHING    Category = 1
	Category_BOOKS       Category = 2
	Category_HOME_GARDEN Category = 3
	Category_SPORTS      Category = 4
	Category_TOYS        Category = 5
)

// Enum value maps for Category.
var (
	Category_name = map[int32]string{
		0: "ELECTRONICS",
		1: "CLOTHING",
		2: "BOOKS",
		3: "HOME_GARDEN",
		4: "SPORTS",
		5: "TOYS",
	}
	Category_value = map[string]int32{
		"ELECTRONICS": 0,
		"CLOTHING":    1,
		"BOOKS":       2,
		"HOME_GARDEN": 3,
		"SPORTS":      4,
		"TOYS":        5,
	}
)

func (x Category) Enum() *Category {
	p := new(Category)
	*p = x
	return p
}

func (x Category) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Category) Descriptor() protoreflect.EnumDescriptor {
	return file_products_products_proto_enumTypes[0].Descriptor()
}

func (Category) Type() protoreflect.EnumType {
	return &file_products_products_proto_enumTypes[0]
}

func (x Category) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Category.Descriptor instead.
func (Category) EnumDescriptor() ([]byte, []int) {
	return file_products_products_proto_rawDescGZIP(), []int{0}
}

type GetProductsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Ids              []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	Categories       []Category             `protobuf:"varint,2,rep,packed,name=categories,proto3,enum=products.Category" json:"categories,omitempty"`
	InStockOnly      *wrapperspb.BoolValue  `protobuf:"bytes,3,opt,name=in_stock_only,json=inStockOnly,proto3" json:"in_stock_only,omitempty"`
	AvailableAfter   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=available_after,json=availableAfter,proto3" json:"available_after,omitempty"`
	FieldMask        *graphql.FieldMask     `protobuf:"bytes,5,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	InternalMetadata string                 `protobuf:"bytes,6,opt,name=internal_metadata,json=internalMetadata,proto3" json:"internal_metadata,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetProductsRequest) Reset() {
	*x = GetProductsRequest{}
	mi := &file_products_products_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsRequest) ProtoMessage() {}

func (x *GetProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_products_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsRequest.ProtoReflect.Descriptor instead.
func (*GetProductsRequest) Descriptor() ([]byte, []int) {
	return file_products_products_proto_rawDescGZIP(), []int{0}
}

func (x *GetProductsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *GetProductsRequest) GetCategories() []Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *GetProductsRequest) GetInStockOnly() *wrapperspb.BoolValue {
	if x != nil {
		return x.InStockOnly
	}
	return nil
}

func (x *GetProductsRequest) GetAvailableAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.AvailableAfter
	}
	return nil
}

func (x *GetProductsRequest) GetFieldMask() *graphql.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

func (x *GetProductsRequest) GetInternalMetadata() string {
	if x != nil {
		return x.InternalMetadata
	}
	return ""
}

type GetProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	PageInfo      *graphql.PageInfo      `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsResponse) Reset() {
	*x = GetProductsResponse{}
	mi := &file_products_products_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsResponse) ProtoMessage() {}

func (x *GetProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_products_products_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsResponse.ProtoReflect.Descriptor instead.
func (*GetProductsResponse) Descriptor() ([]byte, []int) {
	return file_products_products_proto_rawDescGZIP(), []int{1}
}

func (x *GetProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *GetProductsResponse) GetPageInfo() *graphql.PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

type GetProductsByCategoryResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Results       map[string]*ProductsByCategory `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsByCategoryResponse) Reset() {
	*x = GetProductsByCategoryResponse{}
	mi := &file_products_products_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsByCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsByCategoryResponse) ProtoMessage() {}

func (x *GetProductsByCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_products_products_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsByCategoryResponse.ProtoReflect.Descriptor instead.
func (*GetProductsByCategoryResponse) Descriptor() ([]byte, []int) {
	return file_products_products_proto_rawDescGZIP(), []int{2}
}

func (x *GetProductsByCategoryResponse) GetResults() map[string]*ProductsByCategory {
	if x != nil {
		return x.Results
	}
	return nil
}

type LoadProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reqs          []*GetProductsRequest  `protobuf:"bytes,1,rep,name=reqs,proto3" json:"reqs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadProductsRequest) Reset() {
	*x = LoadProductsRequest{}
	mi := &file_products_products_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadProductsRequest) ProtoMessage() {}

func (x *LoadProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_products_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadProductsRequest.ProtoReflect.Descriptor instead.
func (*LoadProductsRequest) Descriptor() ([]byte, []int) {
	return file_products_products_proto_rawDescGZIP(), []int{3}
}

func (x *LoadProductsRequest) GetReqs() []*GetProductsRequest {
	if x != nil {
		return x.Reqs
	}
	return nil
}

type LoadProductsResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Results       map[string]*GetProductsResponse `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadProductsResponse) Reset() {
	*x = LoadProductsResponse{}
	mi := &file_products_products_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadProductsResponse) ProtoMessage() {}

func (x *LoadProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_products_products_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadProductsResponse.ProtoReflect.Descriptor instead.
func (*LoadProductsResponse) Descriptor() ([]byte, []int) {
	return file_products_products_proto_rawDescGZIP(), []int{4}
}

func (x *LoadProductsResponse) GetResults() map[string]*GetProductsResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

type SearchProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProductsRequest) Reset() {
	*x = SearchProductsRequest{}
	mi := &file_products_products_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProductsRequest) ProtoMessage() {}

func (x *SearchProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_products_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProductsRequest.ProtoReflect.Descriptor instead.
func (*SearchProductsRequest) Descriptor() ([]byte, []int) {
	return file_products_products_proto_rawDescGZIP(), []int{5}
}

func (x *SearchProductsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchProductsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchProductsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type SearchProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	PageInfo      *graphql.PageInfo      `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProductsResponse) Reset() {
	*x = SearchProductsResponse{}
	mi := &file_products_products_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProductsResponse) ProtoMessage() {}

func (x *SearchProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_products_products_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProductsResponse.ProtoReflect.Descriptor instead.
func (*SearchProductsResponse) Descriptor() ([]byte, []int) {
	return file_products_products_proto_rawDescGZIP(), []int{6}
}

func (x *SearchProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *SearchProductsResponse) GetPageInfo() *graphql.PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

type ProductsByCategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Product             `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductsByCategory) Reset() {
	*x = ProductsByCategory{}
	mi := &file_products_products_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductsByCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductsByCategory) ProtoMessage() {}

func (x *ProductsByCategory) ProtoReflect() protoreflect.Message {
	mi := &file_products_products_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductsByCategory.ProtoReflect.Descriptor instead.
func (*ProductsByCategory) Descriptor() ([]byte, []int) {
	return file_products_products_proto_rawDescGZIP(), []int{7}
}

func (x *ProductsByCategory) GetResults() []*Product {
	if x != nil {
		return x.Results
	}
	return nil
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category      Category               `protobuf:"varint,4,opt,name=category,proto3,enum=products.Category" json:"category,omitempty"`
	Price         *common_example.Money  `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	Inventory     *Inventory             `protobuf:"bytes,6,opt,name=inventory,proto3" json:"inventory,omitempty"`
	Variants      []*ProductVariant      `protobuf:"bytes,7,rep,name=variants,proto3" json:"variants,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Featured      *wrapperspb.BoolValue  `protobuf:"bytes,10,opt,name=featured,proto3" json:"featured,omitempty"`
	SellerId      string                 `protobuf:"bytes,11,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	ImageUrls     []string               `protobuf:"bytes,12,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	Rating        *float32               `protobuf:"fixed32,13,opt,name=rating,proto3,oneof" json:"rating,omitempty"`
	ReviewCount   *int32                 `protobuf:"varint,14,opt,name=review_count,json=reviewCount,proto3,oneof" json:"review_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_products_products_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_products_products_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_products_products_proto_rawDescGZIP(), []int{8}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetCategory() Category {
	if x != nil {
		return x.Category
	}
	return Category_ELECTRONICS
}

func (x *Product) GetPrice() *common_example.Money {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *Product) GetInventory() *Inventory {
	if x != nil {
		return x.Inventory
	}
	return nil
}

func (x *Product) GetVariants() []*ProductVariant {
	if x != nil {
		return x.Variants
	}
	return nil
}

func (x *Product) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Product) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Product) GetFeatured() *wrapperspb.BoolValue {
	if x != nil {
		return x.Featured
	}
	return nil
}

func (x *Product) GetSellerId() string {
	if x != nil {
		return x.SellerId
	}
	return ""
}

func (x *Product) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

func (x *Product) GetRating() float32 {
	if x != nil && x.Rating != nil {
		return *x.Rating
	}
	return 0
}

func (x *Product) GetReviewCount() int32 {
	if x != nil && x.ReviewCount != nil {
		return *x.ReviewCount
	}
	return 0
}

type ProductVariant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sku           string                 `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	Price         *common_example.Money  `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	StockQuantity int32                  `protobuf:"varint,5,opt,name=stock_quantity,json=stockQuantity,proto3" json:"stock_quantity,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,6,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // e.g., "color": "blue", "size": "M"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductVariant) Reset() {
	*x = ProductVariant{}
	mi := &file_products_products_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductVariant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductVariant) ProtoMessage() {}

func (x *ProductVariant) ProtoReflect() protoreflect.Message {
	mi := &file_products_products_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductVariant.ProtoReflect.Descriptor instead.
func (*ProductVariant) Descriptor() ([]byte, []int) {
	return file_products_products_proto_rawDescGZIP(), []int{9}
}

func (x *ProductVariant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductVariant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductVariant) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ProductVariant) GetPrice() *common_example.Money {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *ProductVariant) GetStockQuantity() int32 {
	if x != nil {
		return x.StockQuantity
	}
	return 0
}

func (x *ProductVariant) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type Inventory struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Quantity          int32                  `protobuf:"varint,1,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Reserved          int32                  `protobuf:"varint,2,opt,name=reserved,proto3" json:"reserved,omitempty"`
	WarehouseLocation string                 `protobuf:"bytes,3,opt,name=warehouse_location,json=warehouseLocation,proto3" json:"warehouse_location,omitempty"`
	LastRestocked     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_restocked,json=lastRestocked,proto3" json:"last_restocked,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Inventory) Reset() {
	*x = Inventory{}
	mi := &file_products_products_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inventory) ProtoMessage() {}

func (x *Inventory) ProtoReflect() protoreflect.Message {
	mi := &file_products_products_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inventory.ProtoReflect.Descriptor instead.
func (*Inventory) Descriptor() ([]byte, []int) {
	return file_products_products_proto_rawDescGZIP(), []int{10}
}

func (x *Inventory) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Inventory) GetReserved() int32 {
	if x != nil {
		return x.Reserved
	}
	return 0
}

func (x *Inventory) GetWarehouseLocation() string {
	if x != nil {
		return x.WarehouseLocation
	}
	return ""
}

func (x *Inventory) GetLastRestocked() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRestocked
	}
	return nil
}

// This message is for internal use only and won't appear in GraphQL schema
type InternalProductData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SupplierId    string                 `protobuf:"bytes,1,opt,name=supplier_id,json=supplierId,proto3" json:"supplier_id,omitempty"`
	Cost          float32                `protobuf:"fixed32,2,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalProductData) Reset() {
	*x = InternalProductData{}
	mi := &file_products_products_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalProductData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalProductData) ProtoMessage() {}

func (x *InternalProductData) ProtoReflect() protoreflect.Message {
	mi := &file_products_products_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalProductData.ProtoReflect.Descriptor instead.
func (*InternalProductData) Descriptor() ([]byte, []int) {
	return file_products_products_proto_rawDescGZIP(), []int{11}
}

func (x *InternalProductData) GetSupplierId() string {
	if x != nil {
		return x.SupplierId
	}
	return ""
}

func (x *InternalProductData) GetCost() float32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

var File_products_products_proto protoreflect.FileDescriptor

const file_products_products_proto_rawDesc = "" +
	"\n" +
	"\x17products/products.proto\x12\bproducts\x1a\rgraphql.proto\x1a#common-example/common-example.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe2\x02\n" +
	"\x12GetProductsRequest\x12\x15\n" +
	"\x03ids\x18\x01 \x03(\tB\x03\xc0D\x01R\x03ids\x127\n" +
	"\n" +
	"categories\x18\x02 \x03(\x0e2\x12.products.CategoryB\x03\xc0D\x01R\n" +
	"categories\x12>\n" +
	"\rin_stock_only\x18\x03 \x01(\v2\x1a.google.protobuf.BoolValueR\vinStockOnly\x12C\n" +
	"\x0favailable_after\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0eavailableAfter\x121\n" +
	"\n" +
	"field_mask\x18\x05 \x01(\v2\x12.graphql.FieldMaskR\tfieldMask\x120\n" +
	"\x11internal_metadata\x18\x06 \x01(\tB\x03\xc8D\x01R\x10internalMetadata:\x12\xeaC\x0fProductsRequest\"t\n" +
	"\x13GetProductsResponse\x12-\n" +
	"\bproducts\x18\x01 \x03(\v2\x11.products.ProductR\bproducts\x12.\n" +
	"\tpage_info\x18\x02 \x01(\v2\x11.graphql.PageInfoR\bpageInfo\"\xc9\x01\n" +
	"\x1dGetProductsByCategoryResponse\x12N\n" +
	"\aresults\x18\x01 \x03(\v24.products.GetProductsByCategoryResponse.ResultsEntryR\aresults\x1aX\n" +
	"\fResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.products.ProductsByCategoryR\x05value:\x028\x01\"G\n" +
	"\x13LoadProductsRequest\x120\n" +
	"\x04reqs\x18\x01 \x03(\v2\x1c.products.GetProductsRequestR\x04reqs\"\xb8\x01\n" +
	"\x14LoadProductsResponse\x12E\n" +
	"\aresults\x18\x01 \x03(\v2+.products.LoadProductsResponse.ResultsEntryR\aresults\x1aY\n" +
	"\fResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.products.GetProductsResponseR\x05value:\x028\x01\"e\n" +
	"\x15SearchProductsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x19\n" +
	"\x05limit\x18\x02 \x01(\x05B\x03\xc0D\x01R\x05limit\x12\x1b\n" +
	"\x06cursor\x18\x03 \x01(\tB\x03\xc0D\x01R\x06cursor\"w\n" +
	"\x16SearchProductsResponse\x12-\n" +
	"\bproducts\x18\x01 \x03(\v2\x11.products.ProductR\bproducts\x12.\n" +
	"\tpage_info\x18\x02 \x01(\v2\x11.graphql.PageInfoR\bpageInfo\"A\n" +
	"\x12ProductsByCategory\x12+\n" +
	"\aresults\x18\x01 \x03(\v2\x11.products.ProductR\aresults\"\xe0\x04\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12.\n" +
	"\bcategory\x18\x04 \x01(\x0e2\x12.products.CategoryR\bcategory\x12+\n" +
	"\x05price\x18\x05 \x01(\v2\x15.common_example.MoneyR\x05price\x121\n" +
	"\tinventory\x18\x06 \x01(\v2\x13.products.InventoryR\tinventory\x124\n" +
	"\bvariants\x18\a \x03(\v2\x18.products.ProductVariantR\bvariants\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x126\n" +
	"\bfeatured\x18\n" +
	" \x01(\v2\x1a.google.protobuf.BoolValueR\bfeatured\x12\x1b\n" +
	"\tseller_id\x18\v \x01(\tR\bsellerId\x12\x1d\n" +
	"\n" +
	"image_urls\x18\f \x03(\tR\timageUrls\x12\x1b\n" +
	"\x06rating\x18\r \x01(\x02H\x00R\x06rating\x88\x01\x01\x12&\n" +
	"\freview_count\x18\x0e \x01(\x05H\x01R\vreviewCount\x88\x01\x01B\t\n" +
	"\a_ratingB\x0f\n" +
	"\r_review_count\"\xa3\x02\n" +
	"\x0eProductVariant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03sku\x18\x03 \x01(\tR\x03sku\x12+\n" +
	"\x05price\x18\x04 \x01(\v2\x15.common_example.MoneyR\x05price\x12%\n" +
	"\x0estock_quantity\x18\x05 \x01(\x05R\rstockQuantity\x12H\n" +
	"\n" +
	"attributes\x18\x06 \x03(\v2(.products.ProductVariant.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb5\x01\n" +
	"\tInventory\x12\x1a\n" +
	"\bquantity\x18\x01 \x01(\x05R\bquantity\x12\x1a\n" +
	"\breserved\x18\x02 \x01(\x05R\breserved\x12-\n" +
	"\x12warehouse_location\x18\x03 \x01(\tR\x11warehouseLocation\x12A\n" +
	"\x0elast_restocked\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rlastRestocked\"O\n" +
	"\x13InternalProductData\x12\x1f\n" +
	"\vsupplier_id\x18\x01 \x01(\tR\n" +
	"supplierId\x12\x12\n" +
	"\x04cost\x18\x02 \x01(\x02R\x04cost:\x03\xf8C\x01*[\n" +
	"\bCategory\x12\x0f\n" +
	"\vELECTRONICS\x10\x00\x12\f\n" +
	"\bCLOTHING\x10\x01\x12\t\n" +
	"\x05BOOKS\x10\x02\x12\x0f\n" +
	"\vHOME_GARDEN\x10\x03\x12\n" +
	"\n" +
	"\x06SPORTS\x10\x04\x12\b\n" +
	"\x04TOYS\x10\x052\xf5\x02\n" +
	"\bProducts\x12L\n" +
	"\vgetProducts\x12\x1c.products.GetProductsRequest\x1a\x1d.products.GetProductsResponse\"\x00\x12\\\n" +
	"\x15getProductsByCategory\x12\x15.graphql.BatchRequest\x1a'.products.GetProductsByCategoryResponse\"\x03\xd0D\x01\x12R\n" +
	"\floadProducts\x12\x1d.products.LoadProductsRequest\x1a\x1e.products.LoadProductsResponse\"\x03\xd0D\x01\x12U\n" +
	"\x0esearchProducts\x12\x1f.products.SearchProductsRequest\x1a .products.SearchProductsResponse\"\x00\x1a\x12\x82D\x0flocalhost:50051B\x1bZ\x19example/products;productsb\x06proto3"

var (
	file_products_products_proto_rawDescOnce sync.Once
	file_products_products_proto_rawDescData []byte
)

func file_products_products_proto_rawDescGZIP() []byte {
	file_products_products_proto_rawDescOnce.Do(func() {
		file_products_products_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_products_products_proto_rawDesc), len(file_products_products_proto_rawDesc)))
	})
	return file_products_products_proto_rawDescData
}

var file_products_products_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_products_products_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_products_products_proto_goTypes = []any{
	(Category)(0),                         // 0: products.Category
	(*GetProductsRequest)(nil),            // 1: products.GetProductsRequest
	(*GetProductsResponse)(nil),           // 2: products.GetProductsResponse
	(*GetProductsByCategoryResponse)(nil), // 3: products.GetProductsByCategoryResponse
	(*LoadProductsRequest)(nil),           // 4: products.LoadProductsRequest
	(*LoadProductsResponse)(nil),          // 5: products.LoadProductsResponse
	(*SearchProductsRequest)(nil),         // 6: products.SearchProductsRequest
	(*SearchProductsResponse)(nil),        // 7: products.SearchProductsResponse
	(*ProductsByCategory)(nil),            // 8: products.ProductsByCategory
	(*Product)(nil),                       // 9: products.Product
	(*ProductVariant)(nil),                // 10: products.ProductVariant
	(*Inventory)(nil),                     // 11: products.Inventory
	(*InternalProductData)(nil),           // 12: products.InternalProductData
	nil,                                   // 13: products.GetProductsByCategoryResponse.ResultsEntry
	nil,                                   // 14: products.LoadProductsResponse.ResultsEntry
	nil,                                   // 15: products.ProductVariant.AttributesEntry
	(*wrapperspb.BoolValue)(nil),          // 16: google.protobuf.BoolValue
	(*timestamppb.Timestamp)(nil),         // 17: google.protobuf.Timestamp
	(*graphql.FieldMask)(nil),             // 18: graphql.FieldMask
	(*graphql.PageInfo)(nil),              // 19: graphql.PageInfo
	(*common_example.Money)(nil),          // 20: common_example.Money
	(*graphql.BatchRequest)(nil),          // 21: graphql.BatchRequest
}
var file_products_products_proto_depIdxs = []int32{
	0,  // 0: products.GetProductsRequest.categories:type_name -> products.Category
	16, // 1: products.GetProductsRequest.in_stock_only:type_name -> google.protobuf.BoolValue
	17, // 2: products.GetProductsRequest.available_after:type_name -> google.protobuf.Timestamp
	18, // 3: products.GetProductsRequest.field_mask:type_name -> graphql.FieldMask
	9,  // 4: products.GetProductsResponse.products:type_name -> products.Product
	19, // 5: products.GetProductsResponse.page_info:type_name -> graphql.PageInfo
	13, // 6: products.GetProductsByCategoryResponse.results:type_name -> products.GetProductsByCategoryResponse.ResultsEntry
	1,  // 7: products.LoadProductsRequest.reqs:type_name -> products.GetProductsRequest
	14, // 8: products.LoadProductsResponse.results:type_name -> products.LoadProductsResponse.ResultsEntry
	9,  // 9: products.SearchProductsResponse.products:type_name -> products.Product
	19, // 10: products.SearchProductsResponse.page_info:type_name -> graphql.PageInfo
	9,  // 11: products.ProductsByCategory.results:type_name -> products.Product
	0,  // 12: products.Product.category:type_name -> products.Category
	20, // 13: products.Product.price:type_name -> common_example.Money
	11, // 14: products.Product.inventory:type_name -> products.Inventory
	10, // 15: products.Product.variants:type_name -> products.ProductVariant
	17, // 16: products.Product.created_at:type_name -> google.protobuf.Timestamp
	17, // 17: products.Product.updated_at:type_name -> google.protobuf.Timestamp
	16, // 18: products.Product.featured:type_name -> google.protobuf.BoolValue
	20, // 19: products.ProductVariant.price:type_name -> common_example.Money
	15, // 20: products.ProductVariant.attributes:type_name -> products.ProductVariant.AttributesEntry
	17, // 21: products.Inventory.last_restocked:type_name -> google.protobuf.Timestamp
	8,  // 22: products.GetProductsByCategoryResponse.ResultsEntry.value:type_name -> products.ProductsByCategory
	2,  // 23: products.LoadProductsResponse.ResultsEntry.value:type_name -> products.GetProductsResponse
	1,  // 24: products.Products.getProducts:input_type -> products.GetProductsRequest
	21, // 25: products.Products.getProductsByCategory:input_type -> graphql.BatchRequest
	4,  // 26: products.Products.loadProducts:input_type -> products.LoadProductsRequest
	6,  // 27: products.Products.searchProducts:input_type -> products.SearchProductsRequest
	2,  // 28: products.Products.getProducts:output_type -> products.GetProductsResponse
	3,  // 29: products.Products.getProductsByCategory:output_type -> products.GetProductsByCategoryResponse
	5,  // 30: products.Products.loadProducts:output_type -> products.LoadProductsResponse
	7,  // 31: products.Products.searchProducts:output_type -> products.SearchProductsResponse
	28, // [28:32] is the sub-list for method output_type
	24, // [24:28] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_products_products_proto_init() }
func file_products_products_proto_init() {
	if File_products_products_proto != nil {
		return
	}
	file_products_products_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_products_products_proto_rawDesc), len(file_products_products_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_products_products_proto_goTypes,
		DependencyIndexes: file_products_products_proto_depIdxs,
		EnumInfos:         file_products_products_proto_enumTypes,
		MessageInfos:      file_products_products_proto_msgTypes,
	}.Build()
	File_products_products_proto = out.File
	file_products_products_proto_goTypes = nil
	file_products_products_proto_depIdxs = nil
}
