// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: books.proto

package books

import (
	common_example "github.com/kitt-technology/protoc-gen-graphql/example/common-example"
	_ "github.com/kitt-technology/protoc-gen-graphql/graphql"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Genre int32

const (
	Genre_Fiction   Genre = 0
	Genre_Biography Genre = 1
)

// Enum value maps for Genre.
var (
	Genre_name = map[int32]string{
		0: "Fiction",
		1: "Biography",
	}
	Genre_value = map[string]int32{
		"Fiction":   0,
		"Biography": 1,
	}
)

func (x Genre) Enum() *Genre {
	p := new(Genre)
	*p = x
	return p
}

func (x Genre) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Genre) Descriptor() protoreflect.EnumDescriptor {
	return file_books_proto_enumTypes[0].Descriptor()
}

func (Genre) Type() protoreflect.EnumType {
	return &file_books_proto_enumTypes[0]
}

func (x Genre) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Genre.Descriptor instead.
func (Genre) EnumDescriptor() ([]byte, []int) {
	return file_books_proto_rawDescGZIP(), []int{0}
}

type DoNothing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoNothing) Reset() {
	*x = DoNothing{}
	mi := &file_books_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoNothing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoNothing) ProtoMessage() {}

func (x *DoNothing) ProtoReflect() protoreflect.Message {
	mi := &file_books_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoNothing.ProtoReflect.Descriptor instead.
func (*DoNothing) Descriptor() ([]byte, []int) {
	return file_books_proto_rawDescGZIP(), []int{0}
}

type GetBooksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	HardbackOnly  *wrapperspb.BoolValue  `protobuf:"bytes,2,opt,name=hardback_only,json=hardbackOnly,proto3" json:"hardback_only,omitempty"`
	Genres        []Genre                `protobuf:"varint,3,rep,packed,name=genres,proto3,enum=books.Genre" json:"genres,omitempty"`
	ReleasedAfter *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=released_after,json=releasedAfter,proto3" json:"released_after,omitempty"`
	IgnoreMe      string                 `protobuf:"bytes,5,opt,name=ignore_me,json=ignoreMe,proto3" json:"ignore_me,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBooksRequest) Reset() {
	*x = GetBooksRequest{}
	mi := &file_books_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBooksRequest) ProtoMessage() {}

func (x *GetBooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_books_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBooksRequest.ProtoReflect.Descriptor instead.
func (*GetBooksRequest) Descriptor() ([]byte, []int) {
	return file_books_proto_rawDescGZIP(), []int{1}
}

func (x *GetBooksRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *GetBooksRequest) GetHardbackOnly() *wrapperspb.BoolValue {
	if x != nil {
		return x.HardbackOnly
	}
	return nil
}

func (x *GetBooksRequest) GetGenres() []Genre {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *GetBooksRequest) GetReleasedAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.ReleasedAfter
	}
	return nil
}

func (x *GetBooksRequest) GetIgnoreMe() string {
	if x != nil {
		return x.IgnoreMe
	}
	return ""
}

type GetBooksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Books         []*Book                `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBooksResponse) Reset() {
	*x = GetBooksResponse{}
	mi := &file_books_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBooksResponse) ProtoMessage() {}

func (x *GetBooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_books_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBooksResponse.ProtoReflect.Descriptor instead.
func (*GetBooksResponse) Descriptor() ([]byte, []int) {
	return file_books_proto_rawDescGZIP(), []int{2}
}

func (x *GetBooksResponse) GetBooks() []*Book {
	if x != nil {
		return x.Books
	}
	return nil
}

type GetBooksByAuthorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBooksByAuthorRequest) Reset() {
	*x = GetBooksByAuthorRequest{}
	mi := &file_books_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBooksByAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBooksByAuthorRequest) ProtoMessage() {}

func (x *GetBooksByAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_books_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBooksByAuthorRequest.ProtoReflect.Descriptor instead.
func (*GetBooksByAuthorRequest) Descriptor() ([]byte, []int) {
	return file_books_proto_rawDescGZIP(), []int{3}
}

func (x *GetBooksByAuthorRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type GetBooksByAuthorResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Results       map[string]*BooksByAuthor `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBooksByAuthorResponse) Reset() {
	*x = GetBooksByAuthorResponse{}
	mi := &file_books_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBooksByAuthorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBooksByAuthorResponse) ProtoMessage() {}

func (x *GetBooksByAuthorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_books_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBooksByAuthorResponse.ProtoReflect.Descriptor instead.
func (*GetBooksByAuthorResponse) Descriptor() ([]byte, []int) {
	return file_books_proto_rawDescGZIP(), []int{4}
}

func (x *GetBooksByAuthorResponse) GetResults() map[string]*BooksByAuthor {
	if x != nil {
		return x.Results
	}
	return nil
}

type GetBooksBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reqs          []*GetBooksRequest     `protobuf:"bytes,1,rep,name=reqs,proto3" json:"reqs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBooksBatchRequest) Reset() {
	*x = GetBooksBatchRequest{}
	mi := &file_books_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBooksBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBooksBatchRequest) ProtoMessage() {}

func (x *GetBooksBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_books_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBooksBatchRequest.ProtoReflect.Descriptor instead.
func (*GetBooksBatchRequest) Descriptor() ([]byte, []int) {
	return file_books_proto_rawDescGZIP(), []int{5}
}

func (x *GetBooksBatchRequest) GetReqs() []*GetBooksRequest {
	if x != nil {
		return x.Reqs
	}
	return nil
}

type GetBooksBatchResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Results       map[string]*GetBooksResponse `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBooksBatchResponse) Reset() {
	*x = GetBooksBatchResponse{}
	mi := &file_books_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBooksBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBooksBatchResponse) ProtoMessage() {}

func (x *GetBooksBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_books_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBooksBatchResponse.ProtoReflect.Descriptor instead.
func (*GetBooksBatchResponse) Descriptor() ([]byte, []int) {
	return file_books_proto_rawDescGZIP(), []int{6}
}

func (x *GetBooksBatchResponse) GetResults() map[string]*GetBooksResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

type BooksByAuthor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Book                `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BooksByAuthor) Reset() {
	*x = BooksByAuthor{}
	mi := &file_books_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BooksByAuthor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BooksByAuthor) ProtoMessage() {}

func (x *BooksByAuthor) ProtoReflect() protoreflect.Message {
	mi := &file_books_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BooksByAuthor.ProtoReflect.Descriptor instead.
func (*BooksByAuthor) Descriptor() ([]byte, []int) {
	return file_books_proto_rawDescGZIP(), []int{7}
}

func (x *BooksByAuthor) GetResults() []*Book {
	if x != nil {
		return x.Results
	}
	return nil
}

type Book struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AuthorId      string                 `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Genre         Genre                  `protobuf:"varint,4,opt,name=genre,proto3,enum=books.Genre" json:"genre,omitempty"`
	ReleaseDate   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	Price         float32                `protobuf:"fixed32,6,opt,name=price,proto3" json:"price,omitempty"`
	Copies        *int64                 `protobuf:"varint,7,opt,name=copies,proto3,oneof" json:"copies,omitempty"`
	PriceTwo      *common_example.Money  `protobuf:"bytes,8,opt,name=price_two,json=priceTwo,proto3" json:"price_two,omitempty"`
	IsSigned      *wrapperspb.BoolValue  `protobuf:"bytes,9,opt,name=is_signed,json=isSigned,proto3" json:"is_signed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_books_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_books_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_books_proto_rawDescGZIP(), []int{8}
}

func (x *Book) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Book) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Book) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Book) GetGenre() Genre {
	if x != nil {
		return x.Genre
	}
	return Genre_Fiction
}

func (x *Book) GetReleaseDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ReleaseDate
	}
	return nil
}

func (x *Book) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Book) GetCopies() int64 {
	if x != nil && x.Copies != nil {
		return *x.Copies
	}
	return 0
}

func (x *Book) GetPriceTwo() *common_example.Money {
	if x != nil {
		return x.PriceTwo
	}
	return nil
}

func (x *Book) GetIsSigned() *wrapperspb.BoolValue {
	if x != nil {
		return x.IsSigned
	}
	return nil
}

type SkipMe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OhNo          string                 `protobuf:"bytes,1,opt,name=oh_no,json=ohNo,proto3" json:"oh_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkipMe) Reset() {
	*x = SkipMe{}
	mi := &file_books_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkipMe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkipMe) ProtoMessage() {}

func (x *SkipMe) ProtoReflect() protoreflect.Message {
	mi := &file_books_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkipMe.ProtoReflect.Descriptor instead.
func (*SkipMe) Descriptor() ([]byte, []int) {
	return file_books_proto_rawDescGZIP(), []int{9}
}

func (x *SkipMe) GetOhNo() string {
	if x != nil {
		return x.OhNo
	}
	return ""
}

var File_books_proto protoreflect.FileDescriptor

const file_books_proto_rawDesc = "" +
	"\n" +
	"\vbooks.proto\x12\x05books\x1a\rgraphql.proto\x1a#common-example/common-example.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\v\n" +
	"\tDoNothing\"\x85\x02\n" +
	"\x0fGetBooksRequest\x12\x15\n" +
	"\x03ids\x18\x01 \x03(\tB\x03\xc0D\x01R\x03ids\x12?\n" +
	"\rhardback_only\x18\x02 \x01(\v2\x1a.google.protobuf.BoolValueR\fhardbackOnly\x12$\n" +
	"\x06genres\x18\x03 \x03(\x0e2\f.books.GenreR\x06genres\x12A\n" +
	"\x0ereleased_after\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rreleasedAfter\x12 \n" +
	"\tignore_me\x18\x05 \x01(\tB\x03\xc8D\x01R\bignoreMe:\x0f\xeaC\fBooksRequest\"5\n" +
	"\x10GetBooksResponse\x12!\n" +
	"\x05books\x18\x01 \x03(\v2\v.books.BookR\x05books\"-\n" +
	"\x17GetBooksByAuthorRequest\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\"\xb4\x01\n" +
	"\x18GetBooksByAuthorResponse\x12F\n" +
	"\aresults\x18\x01 \x03(\v2,.books.GetBooksByAuthorResponse.ResultsEntryR\aresults\x1aP\n" +
	"\fResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.books.BooksByAuthorR\x05value:\x028\x01\"B\n" +
	"\x14GetBooksBatchRequest\x12*\n" +
	"\x04reqs\x18\x01 \x03(\v2\x16.books.GetBooksRequestR\x04reqs\"\xb1\x01\n" +
	"\x15GetBooksBatchResponse\x12C\n" +
	"\aresults\x18\x01 \x03(\v2).books.GetBooksBatchResponse.ResultsEntryR\aresults\x1aS\n" +
	"\fResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.books.GetBooksResponseR\x05value:\x028\x01\"6\n" +
	"\rBooksByAuthor\x12%\n" +
	"\aresults\x18\x02 \x03(\v2\v.books.BookR\aresults\"\xd5\x02\n" +
	"\x04Book\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\tR\bauthorId\x12\"\n" +
	"\x05genre\x18\x04 \x01(\x0e2\f.books.GenreR\x05genre\x12=\n" +
	"\frelease_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vreleaseDate\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x02R\x05price\x12\x1b\n" +
	"\x06copies\x18\a \x01(\x03H\x00R\x06copies\x88\x01\x01\x122\n" +
	"\tprice_two\x18\b \x01(\v2\x15.common_example.MoneyR\bpriceTwo\x127\n" +
	"\tis_signed\x18\t \x01(\v2\x1a.google.protobuf.BoolValueR\bisSignedB\t\n" +
	"\a_copies\"\"\n" +
	"\x06SkipMe\x12\x13\n" +
	"\x05oh_no\x18\x01 \x01(\tR\x04ohNo:\x03\xf8C\x01*#\n" +
	"\x05Genre\x12\v\n" +
	"\aFiction\x10\x00\x12\r\n" +
	"\tBiography\x10\x012\x85\x02\n" +
	"\x05Books\x12=\n" +
	"\bgetBooks\x12\x16.books.GetBooksRequest\x1a\x17.books.GetBooksResponse\"\x00\x12X\n" +
	"\x10getBooksByAuthor\x12\x1e.books.GetBooksByAuthorRequest\x1a\x1f.books.GetBooksByAuthorResponse\"\x03\xd0D\x01\x12O\n" +
	"\rgetBooksBatch\x12\x1b.books.GetBooksBatchRequest\x1a\x1c.books.GetBooksBatchResponse\"\x03\xd0D\x01\x1a\x12\x82D\x0flocalhost:50051B\x15Z\x13example/books;booksb\x06proto3"

var (
	file_books_proto_rawDescOnce sync.Once
	file_books_proto_rawDescData []byte
)

func file_books_proto_rawDescGZIP() []byte {
	file_books_proto_rawDescOnce.Do(func() {
		file_books_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_books_proto_rawDesc), len(file_books_proto_rawDesc)))
	})
	return file_books_proto_rawDescData
}

var file_books_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_books_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_books_proto_goTypes = []any{
	(Genre)(0),                       // 0: books.Genre
	(*DoNothing)(nil),                // 1: books.DoNothing
	(*GetBooksRequest)(nil),          // 2: books.GetBooksRequest
	(*GetBooksResponse)(nil),         // 3: books.GetBooksResponse
	(*GetBooksByAuthorRequest)(nil),  // 4: books.GetBooksByAuthorRequest
	(*GetBooksByAuthorResponse)(nil), // 5: books.GetBooksByAuthorResponse
	(*GetBooksBatchRequest)(nil),     // 6: books.GetBooksBatchRequest
	(*GetBooksBatchResponse)(nil),    // 7: books.GetBooksBatchResponse
	(*BooksByAuthor)(nil),            // 8: books.BooksByAuthor
	(*Book)(nil),                     // 9: books.Book
	(*SkipMe)(nil),                   // 10: books.SkipMe
	nil,                              // 11: books.GetBooksByAuthorResponse.ResultsEntry
	nil,                              // 12: books.GetBooksBatchResponse.ResultsEntry
	(*wrapperspb.BoolValue)(nil),     // 13: google.protobuf.BoolValue
	(*timestamppb.Timestamp)(nil),    // 14: google.protobuf.Timestamp
	(*common_example.Money)(nil),     // 15: common_example.Money
}
var file_books_proto_depIdxs = []int32{
	13, // 0: books.GetBooksRequest.hardback_only:type_name -> google.protobuf.BoolValue
	0,  // 1: books.GetBooksRequest.genres:type_name -> books.Genre
	14, // 2: books.GetBooksRequest.released_after:type_name -> google.protobuf.Timestamp
	9,  // 3: books.GetBooksResponse.books:type_name -> books.Book
	11, // 4: books.GetBooksByAuthorResponse.results:type_name -> books.GetBooksByAuthorResponse.ResultsEntry
	2,  // 5: books.GetBooksBatchRequest.reqs:type_name -> books.GetBooksRequest
	12, // 6: books.GetBooksBatchResponse.results:type_name -> books.GetBooksBatchResponse.ResultsEntry
	9,  // 7: books.BooksByAuthor.results:type_name -> books.Book
	0,  // 8: books.Book.genre:type_name -> books.Genre
	14, // 9: books.Book.release_date:type_name -> google.protobuf.Timestamp
	15, // 10: books.Book.price_two:type_name -> common_example.Money
	13, // 11: books.Book.is_signed:type_name -> google.protobuf.BoolValue
	8,  // 12: books.GetBooksByAuthorResponse.ResultsEntry.value:type_name -> books.BooksByAuthor
	3,  // 13: books.GetBooksBatchResponse.ResultsEntry.value:type_name -> books.GetBooksResponse
	2,  // 14: books.Books.getBooks:input_type -> books.GetBooksRequest
	4,  // 15: books.Books.getBooksByAuthor:input_type -> books.GetBooksByAuthorRequest
	6,  // 16: books.Books.getBooksBatch:input_type -> books.GetBooksBatchRequest
	3,  // 17: books.Books.getBooks:output_type -> books.GetBooksResponse
	5,  // 18: books.Books.getBooksByAuthor:output_type -> books.GetBooksByAuthorResponse
	7,  // 19: books.Books.getBooksBatch:output_type -> books.GetBooksBatchResponse
	17, // [17:20] is the sub-list for method output_type
	14, // [14:17] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_books_proto_init() }
func file_books_proto_init() {
	if File_books_proto != nil {
		return
	}
	file_books_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_books_proto_rawDesc), len(file_books_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_books_proto_goTypes,
		DependencyIndexes: file_books_proto_depIdxs,
		EnumInfos:         file_books_proto_enumTypes,
		MessageInfos:      file_books_proto_msgTypes,
	}.Build()
	File_books_proto = out.File
	file_books_proto_goTypes = nil
	file_books_proto_depIdxs = nil
}
