version: 2
workflows:
  version: 2
  ci:
    jobs:
      - test: {}
  cd:
    jobs:
      - release:
          # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
jobs:
  test:
    docker:
      - image: kittoffices/protoc-gen-graphql

    steps:
      - checkout
      - run: make test

  release:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash