blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/kitt-technology/protoc-gen-graphql/discussions
    about: Ask questions or discuss ideas with the community