// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: graphql/graphql.proto

package graphql

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRequest) Reset() {
	*x = BatchRequest{}
	mi := &file_graphql_graphql_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRequest) ProtoMessage() {}

func (x *BatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graphql_graphql_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRequest.ProtoReflect.Descriptor instead.
func (*BatchRequest) Descriptor() ([]byte, []int) {
	return file_graphql_graphql_proto_rawDescGZIP(), []int{0}
}

func (x *BatchRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type PageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCount    int32                  `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	EndCursor     string                 `protobuf:"bytes,2,opt,name=end_cursor,json=endCursor,proto3" json:"end_cursor,omitempty"`
	HasNextPage   bool                   `protobuf:"varint,3,opt,name=has_next_page,json=hasNextPage,proto3" json:"has_next_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageInfo) Reset() {
	*x = PageInfo{}
	mi := &file_graphql_graphql_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInfo) ProtoMessage() {}

func (x *PageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_graphql_graphql_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInfo.ProtoReflect.Descriptor instead.
func (*PageInfo) Descriptor() ([]byte, []int) {
	return file_graphql_graphql_proto_rawDescGZIP(), []int{1}
}

func (x *PageInfo) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *PageInfo) GetEndCursor() string {
	if x != nil {
		return x.EndCursor
	}
	return ""
}

func (x *PageInfo) GetHasNextPage() bool {
	if x != nil {
		return x.HasNextPage
	}
	return false
}

type FieldMask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paths         []string               `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	PathsMap      map[string]bool        `protobuf:"bytes,2,rep,name=paths_map,json=pathsMap,proto3" json:"paths_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldMask) Reset() {
	*x = FieldMask{}
	mi := &file_graphql_graphql_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldMask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldMask) ProtoMessage() {}

func (x *FieldMask) ProtoReflect() protoreflect.Message {
	mi := &file_graphql_graphql_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldMask.ProtoReflect.Descriptor instead.
func (*FieldMask) Descriptor() ([]byte, []int) {
	return file_graphql_graphql_proto_rawDescGZIP(), []int{2}
}

func (x *FieldMask) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *FieldMask) GetPathsMap() map[string]bool {
	if x != nil {
		return x.PathsMap
	}
	return nil
}

var file_graphql_graphql_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         1085,
		Name:          "graphql.object_name",
		Tag:           "bytes,1085,opt,name=object_name",
		Filename:      "graphql/graphql.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1086,
		Name:          "graphql.mutation",
		Tag:           "varint,1086,opt,name=mutation",
		Filename:      "graphql/graphql.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1087,
		Name:          "graphql.skip_message",
		Tag:           "varint,1087,opt,name=skip_message",
		Filename:      "graphql/graphql.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1055,
		Name:          "graphql.disabled",
		Tag:           "varint,1055,opt,name=disabled",
		Filename:      "graphql/graphql.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         1056,
		Name:          "graphql.package",
		Tag:           "bytes,1056,opt,name=package",
		Filename:      "graphql/graphql.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         1088,
		Name:          "graphql.host",
		Tag:           "bytes,1088,opt,name=host",
		Filename:      "graphql/graphql.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         1086,
		Name:          "graphql.enum_name",
		Tag:           "bytes,1086,opt,name=enum_name",
		Filename:      "graphql/graphql.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1096,
		Name:          "graphql.optional",
		Tag:           "varint,1096,opt,name=optional",
		Filename:      "graphql/graphql.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1097,
		Name:          "graphql.skip_field",
		Tag:           "varint,1097,opt,name=skip_field",
		Filename:      "graphql/graphql.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1098,
		Name:          "graphql.batch_loader",
		Tag:           "varint,1098,opt,name=batch_loader",
		Filename:      "graphql/graphql.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional string object_name = 1085;
	E_ObjectName = &file_graphql_graphql_proto_extTypes[0]
	// optional bool mutation = 1086;
	E_Mutation = &file_graphql_graphql_proto_extTypes[1]
	// optional bool skip_message = 1087;
	E_SkipMessage = &file_graphql_graphql_proto_extTypes[2]
)

// Extension fields to descriptorpb.FileOptions.
var (
	// optional bool disabled = 1055;
	E_Disabled = &file_graphql_graphql_proto_extTypes[3]
	// optional string package = 1056;
	E_Package = &file_graphql_graphql_proto_extTypes[4]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional string host = 1088;
	E_Host = &file_graphql_graphql_proto_extTypes[5]
)

// Extension fields to descriptorpb.EnumOptions.
var (
	// optional string enum_name = 1086;
	E_EnumName = &file_graphql_graphql_proto_extTypes[6]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional bool optional = 1096;
	E_Optional = &file_graphql_graphql_proto_extTypes[7]
	// optional bool skip_field = 1097;
	E_SkipField = &file_graphql_graphql_proto_extTypes[8]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional bool batch_loader = 1098;
	E_BatchLoader = &file_graphql_graphql_proto_extTypes[9]
)

var File_graphql_graphql_proto protoreflect.FileDescriptor

const file_graphql_graphql_proto_rawDesc = "" +
	"\n" +
	"\x15graphql/graphql.proto\x12\agraphql\x1a google/protobuf/descriptor.proto\"\"\n" +
	"\fBatchRequest\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\"n\n" +
	"\bPageInfo\x12\x1f\n" +
	"\vtotal_count\x18\x01 \x01(\x05R\n" +
	"totalCount\x12\x1d\n" +
	"\n" +
	"end_cursor\x18\x02 \x01(\tR\tendCursor\x12\"\n" +
	"\rhas_next_page\x18\x03 \x01(\bR\vhasNextPage\"\x9d\x01\n" +
	"\tFieldMask\x12\x14\n" +
	"\x05paths\x18\x01 \x03(\tR\x05paths\x12=\n" +
	"\tpaths_map\x18\x02 \x03(\v2 .graphql.FieldMask.PathsMapEntryR\bpathsMap\x1a;\n" +
	"\rPathsMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01:A\n" +
	"\vobject_name\x12\x1f.google.protobuf.MessageOptions\x18\xbd\b \x01(\tR\n" +
	"objectName:<\n" +
	"\bmutation\x12\x1f.google.protobuf.MessageOptions\x18\xbe\b \x01(\bR\bmutation:C\n" +
	"\fskip_message\x12\x1f.google.protobuf.MessageOptions\x18\xbf\b \x01(\bR\vskipMessage:9\n" +
	"\bdisabled\x12\x1c.google.protobuf.FileOptions\x18\x9f\b \x01(\bR\bdisabled:7\n" +
	"\apackage\x12\x1c.google.protobuf.FileOptions\x18\xa0\b \x01(\tR\apackage:4\n" +
	"\x04host\x12\x1f.google.protobuf.ServiceOptions\x18\xc0\b \x01(\tR\x04host::\n" +
	"\tenum_name\x12\x1c.google.protobuf.EnumOptions\x18\xbe\b \x01(\tR\benumName::\n" +
	"\boptional\x12\x1d.google.protobuf.FieldOptions\x18\xc8\b \x01(\bR\boptional:=\n" +
	"\n" +
	"skip_field\x12\x1d.google.protobuf.FieldOptions\x18\xc9\b \x01(\bR\tskipField:B\n" +
	"\fbatch_loader\x12\x1e.google.protobuf.MethodOptions\x18\xca\b \x01(\bR\vbatchLoaderB7Z5github.com/kitt-technology/protoc-gen-graphql/graphqlb\x06proto3"

var (
	file_graphql_graphql_proto_rawDescOnce sync.Once
	file_graphql_graphql_proto_rawDescData []byte
)

func file_graphql_graphql_proto_rawDescGZIP() []byte {
	file_graphql_graphql_proto_rawDescOnce.Do(func() {
		file_graphql_graphql_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_graphql_graphql_proto_rawDesc), len(file_graphql_graphql_proto_rawDesc)))
	})
	return file_graphql_graphql_proto_rawDescData
}

var file_graphql_graphql_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_graphql_graphql_proto_goTypes = []any{
	(*BatchRequest)(nil),                // 0: graphql.BatchRequest
	(*PageInfo)(nil),                    // 1: graphql.PageInfo
	(*FieldMask)(nil),                   // 2: graphql.FieldMask
	nil,                                 // 3: graphql.FieldMask.PathsMapEntry
	(*descriptorpb.MessageOptions)(nil), // 4: google.protobuf.MessageOptions
	(*descriptorpb.FileOptions)(nil),    // 5: google.protobuf.FileOptions
	(*descriptorpb.ServiceOptions)(nil), // 6: google.protobuf.ServiceOptions
	(*descriptorpb.EnumOptions)(nil),    // 7: google.protobuf.EnumOptions
	(*descriptorpb.FieldOptions)(nil),   // 8: google.protobuf.FieldOptions
	(*descriptorpb.MethodOptions)(nil),  // 9: google.protobuf.MethodOptions
}
var file_graphql_graphql_proto_depIdxs = []int32{
	3,  // 0: graphql.FieldMask.paths_map:type_name -> graphql.FieldMask.PathsMapEntry
	4,  // 1: graphql.object_name:extendee -> google.protobuf.MessageOptions
	4,  // 2: graphql.mutation:extendee -> google.protobuf.MessageOptions
	4,  // 3: graphql.skip_message:extendee -> google.protobuf.MessageOptions
	5,  // 4: graphql.disabled:extendee -> google.protobuf.FileOptions
	5,  // 5: graphql.package:extendee -> google.protobuf.FileOptions
	6,  // 6: graphql.host:extendee -> google.protobuf.ServiceOptions
	7,  // 7: graphql.enum_name:extendee -> google.protobuf.EnumOptions
	8,  // 8: graphql.optional:extendee -> google.protobuf.FieldOptions
	8,  // 9: graphql.skip_field:extendee -> google.protobuf.FieldOptions
	9,  // 10: graphql.batch_loader:extendee -> google.protobuf.MethodOptions
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	1,  // [1:11] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_graphql_graphql_proto_init() }
func file_graphql_graphql_proto_init() {
	if File_graphql_graphql_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_graphql_graphql_proto_rawDesc), len(file_graphql_graphql_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 10,
			NumServices:   0,
		},
		GoTypes:           file_graphql_graphql_proto_goTypes,
		DependencyIndexes: file_graphql_graphql_proto_depIdxs,
		MessageInfos:      file_graphql_graphql_proto_msgTypes,
		ExtensionInfos:    file_graphql_graphql_proto_extTypes,
	}.Build()
	File_graphql_graphql_proto = out.File
	file_graphql_graphql_proto_goTypes = nil
	file_graphql_graphql_proto_depIdxs = nil
}
