// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: users.proto

package users

import (
	graphql "github.com/kitt-technology/protoc-gen-graphql/graphql"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserType int32

const (
	UserType_CUSTOMER UserType = 0
	UserType_SELLER   UserType = 1
	UserType_ADMIN    UserType = 2
)

// Enum value maps for UserType.
var (
	UserType_name = map[int32]string{
		0: "CUSTOMER",
		1: "SELLER",
		2: "ADMIN",
	}
	UserType_value = map[string]int32{
		"CUSTOMER": 0,
		"SELLER":   1,
		"ADMIN":    2,
	}
)

func (x UserType) Enum() *UserType {
	p := new(UserType)
	*p = x
	return p
}

func (x UserType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserType) Descriptor() protoreflect.EnumDescriptor {
	return file_users_proto_enumTypes[0].Descriptor()
}

func (UserType) Type() protoreflect.EnumType {
	return &file_users_proto_enumTypes[0]
}

func (x UserType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserType.Descriptor instead.
func (UserType) EnumDescriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{0}
}

type AddressType int32

const (
	AddressType_SHIPPING AddressType = 0
	AddressType_BILLING  AddressType = 1
	AddressType_BOTH     AddressType = 2
)

// Enum value maps for AddressType.
var (
	AddressType_name = map[int32]string{
		0: "SHIPPING",
		1: "BILLING",
		2: "BOTH",
	}
	AddressType_value = map[string]int32{
		"SHIPPING": 0,
		"BILLING":  1,
		"BOTH":     2,
	}
)

func (x AddressType) Enum() *AddressType {
	p := new(AddressType)
	*p = x
	return p
}

func (x AddressType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AddressType) Descriptor() protoreflect.EnumDescriptor {
	return file_users_proto_enumTypes[1].Descriptor()
}

func (AddressType) Type() protoreflect.EnumType {
	return &file_users_proto_enumTypes[1]
}

func (x AddressType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AddressType.Descriptor instead.
func (AddressType) EnumDescriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{1}
}

type GetUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	Type          UserType               `protobuf:"varint,2,opt,name=type,proto3,enum=users.UserType" json:"type,omitempty"`
	FieldMask     *graphql.FieldMask     `protobuf:"bytes,3,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersRequest) Reset() {
	*x = GetUsersRequest{}
	mi := &file_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersRequest) ProtoMessage() {}

func (x *GetUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersRequest.ProtoReflect.Descriptor instead.
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{0}
}

func (x *GetUsersRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *GetUsersRequest) GetType() UserType {
	if x != nil {
		return x.Type
	}
	return UserType_CUSTOMER
}

func (x *GetUsersRequest) GetFieldMask() *graphql.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

type GetUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	PageInfo      *graphql.PageInfo      `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersResponse) Reset() {
	*x = GetUsersResponse{}
	mi := &file_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersResponse) ProtoMessage() {}

func (x *GetUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersResponse.ProtoReflect.Descriptor instead.
func (*GetUsersResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{1}
}

func (x *GetUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *GetUsersResponse) GetPageInfo() *graphql.PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

type UsersBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       map[string]*User       `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersBatchResponse) Reset() {
	*x = UsersBatchResponse{}
	mi := &file_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersBatchResponse) ProtoMessage() {}

func (x *UsersBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersBatchResponse.ProtoReflect.Descriptor instead.
func (*UsersBatchResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{2}
}

func (x *UsersBatchResponse) GetResults() map[string]*User {
	if x != nil {
		return x.Results
	}
	return nil
}

type GetUserProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileRequest) Reset() {
	*x = GetUserProfileRequest{}
	mi := &file_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileRequest) ProtoMessage() {}

func (x *GetUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileRequest.ProtoReflect.Descriptor instead.
func (*GetUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Type          UserType               `protobuf:"varint,5,opt,name=type,proto3,enum=users.UserType" json:"type,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastLogin     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	EmailVerified *wrapperspb.BoolValue  `protobuf:"bytes,8,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	Phone         *string                `protobuf:"bytes,9,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_users_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{4}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetType() UserType {
	if x != nil {
		return x.Type
	}
	return UserType_CUSTOMER
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetLastLogin() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLogin
	}
	return nil
}

func (x *User) GetEmailVerified() *wrapperspb.BoolValue {
	if x != nil {
		return x.EmailVerified
	}
	return nil
}

func (x *User) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

type UserProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Addresses     []*Address             `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Preferences   *UserPreferences       `protobuf:"bytes,3,opt,name=preferences,proto3" json:"preferences,omitempty"`
	Loyalty       *LoyaltyInfo           `protobuf:"bytes,4,opt,name=loyalty,proto3" json:"loyalty,omitempty"`
	TotalOrders   int32                  `protobuf:"varint,5,opt,name=total_orders,json=totalOrders,proto3" json:"total_orders,omitempty"`
	MemberSince   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=member_since,json=memberSince,proto3" json:"member_since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_users_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{5}
}

func (x *UserProfile) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserProfile) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *UserProfile) GetPreferences() *UserPreferences {
	if x != nil {
		return x.Preferences
	}
	return nil
}

func (x *UserProfile) GetLoyalty() *LoyaltyInfo {
	if x != nil {
		return x.Loyalty
	}
	return nil
}

func (x *UserProfile) GetTotalOrders() int32 {
	if x != nil {
		return x.TotalOrders
	}
	return 0
}

func (x *UserProfile) GetMemberSince() *timestamppb.Timestamp {
	if x != nil {
		return x.MemberSince
	}
	return nil
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Line1         string                 `protobuf:"bytes,2,opt,name=line1,proto3" json:"line1,omitempty"`
	Line2         string                 `protobuf:"bytes,3,opt,name=line2,proto3" json:"line2,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	StateProvince string                 `protobuf:"bytes,5,opt,name=state_province,json=stateProvince,proto3" json:"state_province,omitempty"`
	PostalCode    string                 `protobuf:"bytes,6,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Country       string                 `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`
	Type          AddressType            `protobuf:"varint,8,opt,name=type,proto3,enum=users.AddressType" json:"type,omitempty"`
	IsDefault     *wrapperspb.BoolValue  `protobuf:"bytes,9,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_users_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{6}
}

func (x *Address) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Address) GetLine1() string {
	if x != nil {
		return x.Line1
	}
	return ""
}

func (x *Address) GetLine2() string {
	if x != nil {
		return x.Line2
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetStateProvince() string {
	if x != nil {
		return x.StateProvince
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetType() AddressType {
	if x != nil {
		return x.Type
	}
	return AddressType_SHIPPING
}

func (x *Address) GetIsDefault() *wrapperspb.BoolValue {
	if x != nil {
		return x.IsDefault
	}
	return nil
}

type UserPreferences struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MarketingEmails    bool                   `protobuf:"varint,1,opt,name=marketing_emails,json=marketingEmails,proto3" json:"marketing_emails,omitempty"`
	PreferredLanguage  string                 `protobuf:"bytes,2,opt,name=preferred_language,json=preferredLanguage,proto3" json:"preferred_language,omitempty"`
	PreferredCurrency  string                 `protobuf:"bytes,3,opt,name=preferred_currency,json=preferredCurrency,proto3" json:"preferred_currency,omitempty"`
	FavoriteCategories []string               `protobuf:"bytes,4,rep,name=favorite_categories,json=favoriteCategories,proto3" json:"favorite_categories,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UserPreferences) Reset() {
	*x = UserPreferences{}
	mi := &file_users_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPreferences) ProtoMessage() {}

func (x *UserPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPreferences.ProtoReflect.Descriptor instead.
func (*UserPreferences) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{7}
}

func (x *UserPreferences) GetMarketingEmails() bool {
	if x != nil {
		return x.MarketingEmails
	}
	return false
}

func (x *UserPreferences) GetPreferredLanguage() string {
	if x != nil {
		return x.PreferredLanguage
	}
	return ""
}

func (x *UserPreferences) GetPreferredCurrency() string {
	if x != nil {
		return x.PreferredCurrency
	}
	return ""
}

func (x *UserPreferences) GetFavoriteCategories() []string {
	if x != nil {
		return x.FavoriteCategories
	}
	return nil
}

type LoyaltyInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Tier               string                 `protobuf:"bytes,1,opt,name=tier,proto3" json:"tier,omitempty"` // Bronze, Silver, Gold, Platinum
	Points             int32                  `protobuf:"varint,2,opt,name=points,proto3" json:"points,omitempty"`
	DiscountPercentage float32                `protobuf:"fixed32,3,opt,name=discount_percentage,json=discountPercentage,proto3" json:"discount_percentage,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LoyaltyInfo) Reset() {
	*x = LoyaltyInfo{}
	mi := &file_users_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoyaltyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoyaltyInfo) ProtoMessage() {}

func (x *LoyaltyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoyaltyInfo.ProtoReflect.Descriptor instead.
func (*LoyaltyInfo) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{8}
}

func (x *LoyaltyInfo) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *LoyaltyInfo) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *LoyaltyInfo) GetDiscountPercentage() float32 {
	if x != nil {
		return x.DiscountPercentage
	}
	return 0
}

var File_users_proto protoreflect.FileDescriptor

const file_users_proto_rawDesc = "" +
	"\n" +
	"\vusers.proto\x12\x05users\x1a\rgraphql.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x85\x01\n" +
	"\x0fGetUsersRequest\x12\x15\n" +
	"\x03ids\x18\x01 \x03(\tB\x03\xc0D\x01R\x03ids\x12(\n" +
	"\x04type\x18\x02 \x01(\x0e2\x0f.users.UserTypeB\x03\xc0D\x01R\x04type\x121\n" +
	"\n" +
	"field_mask\x18\x03 \x01(\v2\x12.graphql.FieldMaskR\tfieldMask\"e\n" +
	"\x10GetUsersResponse\x12!\n" +
	"\x05users\x18\x01 \x03(\v2\v.users.UserR\x05users\x12.\n" +
	"\tpage_info\x18\x02 \x01(\v2\x11.graphql.PageInfoR\bpageInfo\"\x9f\x01\n" +
	"\x12UsersBatchResponse\x12@\n" +
	"\aresults\x18\x01 \x03(\v2&.users.UsersBatchResponse.ResultsEntryR\aresults\x1aG\n" +
	"\fResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12!\n" +
	"\x05value\x18\x02 \x01(\v2\v.users.UserR\x05value:\x028\x01\"0\n" +
	"\x15GetUserProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xf8\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12#\n" +
	"\x04type\x18\x05 \x01(\x0e2\x0f.users.UserTypeR\x04type\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"last_login\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tlastLogin\x12A\n" +
	"\x0eemail_verified\x18\b \x01(\v2\x1a.google.protobuf.BoolValueR\remailVerified\x12\x19\n" +
	"\x05phone\x18\t \x01(\tH\x00R\x05phone\x88\x01\x01:\v\xeaC\bCustomerB\b\n" +
	"\x06_phone\"\x9e\x02\n" +
	"\vUserProfile\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12,\n" +
	"\taddresses\x18\x02 \x03(\v2\x0e.users.AddressR\taddresses\x128\n" +
	"\vpreferences\x18\x03 \x01(\v2\x16.users.UserPreferencesR\vpreferences\x12,\n" +
	"\aloyalty\x18\x04 \x01(\v2\x12.users.LoyaltyInfoR\aloyalty\x12!\n" +
	"\ftotal_orders\x18\x05 \x01(\x05R\vtotalOrders\x12=\n" +
	"\fmember_since\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vmemberSince\"\xa3\x02\n" +
	"\aAddress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05line1\x18\x02 \x01(\tR\x05line1\x12\x19\n" +
	"\x05line2\x18\x03 \x01(\tB\x03\xc0D\x01R\x05line2\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12%\n" +
	"\x0estate_province\x18\x05 \x01(\tR\rstateProvince\x12\x1f\n" +
	"\vpostal_code\x18\x06 \x01(\tR\n" +
	"postalCode\x12\x18\n" +
	"\acountry\x18\a \x01(\tR\acountry\x12&\n" +
	"\x04type\x18\b \x01(\x0e2\x12.users.AddressTypeR\x04type\x129\n" +
	"\n" +
	"is_default\x18\t \x01(\v2\x1a.google.protobuf.BoolValueR\tisDefault\"\xcb\x01\n" +
	"\x0fUserPreferences\x12)\n" +
	"\x10marketing_emails\x18\x01 \x01(\bR\x0fmarketingEmails\x12-\n" +
	"\x12preferred_language\x18\x02 \x01(\tR\x11preferredLanguage\x12-\n" +
	"\x12preferred_currency\x18\x03 \x01(\tR\x11preferredCurrency\x12/\n" +
	"\x13favorite_categories\x18\x04 \x03(\tR\x12favoriteCategories\"j\n" +
	"\vLoyaltyInfo\x12\x12\n" +
	"\x04tier\x18\x01 \x01(\tR\x04tier\x12\x16\n" +
	"\x06points\x18\x02 \x01(\x05R\x06points\x12/\n" +
	"\x13discount_percentage\x18\x03 \x01(\x02R\x12discountPercentage*/\n" +
	"\bUserType\x12\f\n" +
	"\bCUSTOMER\x10\x00\x12\n" +
	"\n" +
	"\x06SELLER\x10\x01\x12\t\n" +
	"\x05ADMIN\x10\x02*2\n" +
	"\vAddressType\x12\f\n" +
	"\bSHIPPING\x10\x00\x12\v\n" +
	"\aBILLING\x10\x01\x12\b\n" +
	"\x04BOTH\x10\x022\xe4\x01\n" +
	"\x05Users\x12=\n" +
	"\bgetUsers\x12\x16.users.GetUsersRequest\x1a\x17.users.GetUsersResponse\"\x00\x12B\n" +
	"\tloadUsers\x12\x15.graphql.BatchRequest\x1a\x19.users.UsersBatchResponse\"\x03\xd0D\x01\x12D\n" +
	"\x0egetUserProfile\x12\x1c.users.GetUserProfileRequest\x1a\x12.users.UserProfile\"\x00\x1a\x12\x82D\x0flocalhost:50052B\x15Z\x13example/users;usersb\x06proto3"

var (
	file_users_proto_rawDescOnce sync.Once
	file_users_proto_rawDescData []byte
)

func file_users_proto_rawDescGZIP() []byte {
	file_users_proto_rawDescOnce.Do(func() {
		file_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_users_proto_rawDesc), len(file_users_proto_rawDesc)))
	})
	return file_users_proto_rawDescData
}

var file_users_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_users_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_users_proto_goTypes = []any{
	(UserType)(0),                 // 0: users.UserType
	(AddressType)(0),              // 1: users.AddressType
	(*GetUsersRequest)(nil),       // 2: users.GetUsersRequest
	(*GetUsersResponse)(nil),      // 3: users.GetUsersResponse
	(*UsersBatchResponse)(nil),    // 4: users.UsersBatchResponse
	(*GetUserProfileRequest)(nil), // 5: users.GetUserProfileRequest
	(*User)(nil),                  // 6: users.User
	(*UserProfile)(nil),           // 7: users.UserProfile
	(*Address)(nil),               // 8: users.Address
	(*UserPreferences)(nil),       // 9: users.UserPreferences
	(*LoyaltyInfo)(nil),           // 10: users.LoyaltyInfo
	nil,                           // 11: users.UsersBatchResponse.ResultsEntry
	(*graphql.FieldMask)(nil),     // 12: graphql.FieldMask
	(*graphql.PageInfo)(nil),      // 13: graphql.PageInfo
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
	(*wrapperspb.BoolValue)(nil),  // 15: google.protobuf.BoolValue
	(*graphql.BatchRequest)(nil),  // 16: graphql.BatchRequest
}
var file_users_proto_depIdxs = []int32{
	0,  // 0: users.GetUsersRequest.type:type_name -> users.UserType
	12, // 1: users.GetUsersRequest.field_mask:type_name -> graphql.FieldMask
	6,  // 2: users.GetUsersResponse.users:type_name -> users.User
	13, // 3: users.GetUsersResponse.page_info:type_name -> graphql.PageInfo
	11, // 4: users.UsersBatchResponse.results:type_name -> users.UsersBatchResponse.ResultsEntry
	0,  // 5: users.User.type:type_name -> users.UserType
	14, // 6: users.User.created_at:type_name -> google.protobuf.Timestamp
	14, // 7: users.User.last_login:type_name -> google.protobuf.Timestamp
	15, // 8: users.User.email_verified:type_name -> google.protobuf.BoolValue
	8,  // 9: users.UserProfile.addresses:type_name -> users.Address
	9,  // 10: users.UserProfile.preferences:type_name -> users.UserPreferences
	10, // 11: users.UserProfile.loyalty:type_name -> users.LoyaltyInfo
	14, // 12: users.UserProfile.member_since:type_name -> google.protobuf.Timestamp
	1,  // 13: users.Address.type:type_name -> users.AddressType
	15, // 14: users.Address.is_default:type_name -> google.protobuf.BoolValue
	6,  // 15: users.UsersBatchResponse.ResultsEntry.value:type_name -> users.User
	2,  // 16: users.Users.getUsers:input_type -> users.GetUsersRequest
	16, // 17: users.Users.loadUsers:input_type -> graphql.BatchRequest
	5,  // 18: users.Users.getUserProfile:input_type -> users.GetUserProfileRequest
	3,  // 19: users.Users.getUsers:output_type -> users.GetUsersResponse
	4,  // 20: users.Users.loadUsers:output_type -> users.UsersBatchResponse
	7,  // 21: users.Users.getUserProfile:output_type -> users.UserProfile
	19, // [19:22] is the sub-list for method output_type
	16, // [16:19] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_users_proto_init() }
func file_users_proto_init() {
	if File_users_proto != nil {
		return
	}
	file_users_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_proto_rawDesc), len(file_users_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_users_proto_goTypes,
		DependencyIndexes: file_users_proto_depIdxs,
		EnumInfos:         file_users_proto_enumTypes,
		MessageInfos:      file_users_proto_msgTypes,
	}.Build()
	File_users_proto = out.File
	file_users_proto_goTypes = nil
	file_users_proto_depIdxs = nil
}
